version: '3'

services:

    # mqtt broker
    mosquitto:
        build: mosquitto
        restart: always
        network_mode: host
        ports:
            - "1883:1883"
            - "9001:9001"

    # zigbee to mqtt bridge
    zigbee2mqtt:
        container_name: zigbee2mqtt
        network_mode: host
        image: koenkk/zigbee2mqtt:latest-dev
        volumes:
            - ./configuration:/app/data                                 # uncomment when running on ssd/hdd
            # - /zigbee2mqtt/zigbee2udp/configuration:/app/data         # uncomment when running on RPi
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        restart: always
        privileged: true
        env_file:
            - variables

    # mqtt to udp bridge
    zigbee2loxone:
        network_mode: host
        build: zigbee2loxone
        restart: always
        env_file:
            - variables

    loxone2zigbee:
        network_mode: host
        build: loxone2zigbee
        ports:
        - 4445
        restart: always
        env_file:
            - variables
