#!/bin/bash

source /etc/rwsync.conf

function saveData() {
    rsync -a --delete $UPPER/ $LOWER/
}

function loadData() {
    rsync -a $LOWER/ $UPPER/
}

function handleExit() {
    saveData
    umount $LOWER
    exit
}

trap handleExit SIGINT SIGTERM EXIT

mkdir -p $UPPER $LOWER
mount $LOWER_DEVICE $LOWER

loadData

while true; do
    sleep $SLEEPTIME
    saveData
done
